language: ruby
rvm:
- 2.3.0
env:
  global:
  - POSTGRES_HOST=localhost
  - REDIS_URL=redis://localhost:6379/2

bundler_args: --without production

before_install:
#  - apt-cache search postgis
  - printenv
  - cat /etc/os-release

install:
  - sudo apt-get install -y $(apt-cache search postgis | awk '/^postgresql-9\.[2-6]-postgis-2.3/{printf " "$1}' )
  - sudo apt-get install -y redis-server

before_script:
#  - dpkg -l |grep post
  - sudo service postgresql restart
  - sudo service redis-server restart
  - redis-cli info
  - psql -U postgres -c "create extension postgis"
#  - psql -U postgres -c "create extension postgis version '2.2'"

script:
  - "bundle install"
  - "bundle exec sidekiq -d -C config/sidekiq.yml -e development"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake test --verbose"

services:
  - postgresql
  - redis-server
