language: ruby
rvm:
- 2.3.0
env:
  global:
  - POSTGRES_HOST=localhost

before_install:
  - apt-cache search postgis

install:
  - sudo apt-get install postgresql-9.5-postgis-2.3
  - psql -U postgres -c "create extension postgis"

before_script:
  - sudo service postgresql restart

script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake test --verbose"

services:
  - postgresql
