language: ruby
rvm:
- 2.3.0
before_script:
  - psql -U postgres -c "create extension postgis"
install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake test --verbose"
services:
  - postgresql
