language: ruby
rvm:
- 2.3.0
env:
  global:
  - POSTGRES_HOST=localhost

before_install:
  - apt-cache search postgis

install:
  - sudo apt-get install -y $(apt-cache search postgis | awk '/^postgresql-9\.[2-6]-postgis-2.3/{printf " "$1}' )

before_script:
  - dpkg -l |grep post
  - sudo service postgresql restart
  - psql -U postgres -c "create extension postgis"

script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake test --verbose"

services:
  - postgresql
