# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 072470a3fd6edc4be9f2531f0c5919f82583ee158d983c627c4648706b482c688eb9f08518be271e1e91edf9fa1a50329ac961aea6f9660db8fbf996bc0e8076
  redis_url: redis://redis:6379/1
  mongo_url: mongo
  mongo_port: 3344

test:
  secret_key_base: 4fcaab6f0af2508ed842631732ffaeabf4f7823c10d8c309ee0a529eb8e6ebb56d4f2dd43e806219b4fe95c4258c419ef1913e2ea017a5032dadec08b236235d
  redis_url: <%= ENV['REDIS_URL_TEST'] || 'redis://localhost:6379' %>
  mongo_url: mongo
  mongo_port: 3344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  mongo_url: <%= ENV['MONGO_URL'] %>
  mongo_port: <%= ENV['MONGO_PORT'] %>
